color: null
fieldLayouts:
  677c5c49-113d-404d-8cde-1a617e1c334c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-15T11:44:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: cec444f7-47d2-416d-8bab-c05e50415459
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-15T11:47:09+00:00'
            elementCondition: null
            fieldUid: dda891de-1c3b-4002-8b43-3ee0c7d19fc5 # Select Author
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a864962-d805-4d96-9f89-2a613d745d36
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-15T11:47:09+00:00'
            elementCondition: null
            fieldUid: cdf26765-b403-4449-8086-e526d5c50b2a # Address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1037ce68-af37-427c-83c0-06dc79ed5b02
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-15T11:47:09+00:00'
            elementCondition: null
            fieldUid: c6f999d6-4930-49f6-9bca-9426a6058f93 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14acd690-c4a4-440c-aebd-c08c8b0a16d5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 57122345-9970-4e7e-815a-0f9d3dff0905
        userCondition: null
handle: author
hasTitleField: false
icon: ''
name: Author
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
