color: null
fieldLayouts:
  acdc71d3-f5b9-4f0e-a2e3-a364e3b5fdd8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-30T20:59:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9302fd12-0e88-4f4f-81a4-58579c9c4b3b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-30T21:01:53+00:00'
            elementCondition: null
            fieldUid: 87655dce-f27c-4a4e-a317-b045a7021d63 # Headline Tag
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 519509e0-cffc-4780-8a9d-a65e1f1b5bb0
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-08-30T21:01:53+00:00'
            elementCondition: null
            fieldUid: e8b13026-7e14-481b-a8ca-dbd098c02b62 # Plain Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a101caea-a8d1-4866-aad9-0ad088714ea6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-30T21:01:53+00:00'
            elementCondition: null
            fieldUid: 90d72bd5-ed0a-4fc4-b5f5-3ed67dac3372 # Entries
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3da05c16-e187-4562-8401-7ad70313fb7a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4384a5bc-4be4-43be-8071-fec682489a9b
        userCondition: null
handle: cta
hasTitleField: true
icon: ''
name: Cta
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
