color: null
fieldLayouts:
  cdf226d3-60d1-4442-aacb-80d94cf0944a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-30T20:47:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1b7c5fa8-9226-415d-8703-2618b4709ea5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-24T19:40:03+00:00'
            elementCondition: null
            fieldUid: 83bea185-c5b5-4e9d-bf5c-ae8eb69ba126 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0ec7e0d-1273-4bcb-af7b-ec0426d2cb42
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-24T19:42:28+00:00'
            elementCondition: null
            fieldUid: dda891de-1c3b-4002-8b43-3ee0c7d19fc5 # Select Author
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a4e6fd4b-fbb2-4467-aaa2-484a53816402
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-30T21:03:06+00:00'
            elementCondition: null
            fieldUid: e8b13026-7e14-481b-a8ca-dbd098c02b62 # Plain Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Intro Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 695c925c-27d4-45a8-af36-6225f3c11c09
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-15T14:24:59+00:00'
            elementCondition: null
            fieldUid: c0ffe0d6-ee6f-45d7-9d5b-cc469270ff26 # Richtext
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b152d5b2-c85f-45be-87b2-1b7e12304238
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-30T21:00:24+00:00'
            elementCondition: null
            fieldUid: 1fb00b26-caa3-453a-a88f-cf3af93d99ab # Content Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 891ea75e-729f-4ed4-a666-16b6b4e93d98
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-30T21:03:06+00:00'
            elementCondition: null
            fieldUid: ffaf40d1-d46f-48eb-b181-b73770a9e058 # Cta
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3f512333-f50e-4248-b198-6d111d38de37
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 55465b4b-68cd-4012-990f-22ec6ce7026f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-15T16:20:21+00:00'
            elementCondition: null
            fieldUid: 1cd93979-2972-43fc-8416-fe5ad476f216 # SEO Settingss
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da21df81-b6a5-46bf-99e2-825d9f4ef139
            userCondition: null
            warning: null
            width: 100
        name: 'Test Tab'
        uid: dd4a003a-ecb9-46bd-ab8c-77d39cc5d0fb
        userCondition: null
handle: home
hasTitleField: true
icon: null
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
