color: null
fieldLayouts:
  000be692-ac90-48c9-b215-0e70796bcd30:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-23T15:00:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 4a59644d-33ed-4fbc-87e0-7b3ac631d6fa
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-23T15:02:12+00:00'
            elementCondition: null
            fieldUid: 922c9738-46cf-41f0-942a-1586792ccad2 # Hyper Field
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 817f1d1a-0886-48ff-adeb-3aa20cfca762
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e79ad230-33d7-4c00-b6a4-6e4de7cf974a
        userCondition: null
handle: hyperLink
hasTitleField: false
icon: ''
name: 'hyper Link'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
