color: null
fieldLayouts:
  02659e80-ab13-46e2-80cf-c8e2b764a32f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-30T20:54:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5e3403ce-e509-49dc-bc6e-6bd283ad3459
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-30T20:57:09+00:00'
            elementCondition: null
            fieldUid: 83bea185-c5b5-4e9d-bf5c-ae8eb69ba126 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3dff1270-b367-4f25-8257-20a45f0a4ac5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-30T20:57:09+00:00'
            elementCondition: null
            fieldUid: e8b13026-7e14-481b-a8ca-dbd098c02b62 # Plain Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eef8547e-84f8-4d24-a474-d8ee7b891f08
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7605eb3f-990a-474f-8f8f-472e14257e4c
        userCondition: null
handle: imageText
hasTitleField: false
icon: ''
name: 'Image Text'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
