color: null
fieldLayouts:
  0763752c-d777-4f14-8606-00b993bebaad:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-09-15T14:18:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 662b9ac6-76f5-4229-b411-81638bd48fdc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-09-15T14:20:36+00:00'
            elementCondition: null
            fieldUid: 7e655b93-2efb-47b9-b615-a5ed91e919f9 # Link Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6e3a693-bc50-478d-86f0-bb3595d50c05
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-15T14:20:36+00:00'
            elementCondition: null
            fieldUid: 73224fd0-62f0-4246-bc68-8512e2c9a5be # Open in New Tab
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88527daf-5f5d-4dbf-8bfd-82c2847ee589
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-09-15T14:20:36+00:00'
            elementCondition: null
            fieldUid: c6f999d6-4930-49f6-9bca-9426a6058f93 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cba886c2-8a6a-4418-aada-abd7fd2f0c22
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e8128fb7-2dd7-47af-92bb-0ff543186d96
        userCondition: null
handle: link
hasTitleField: false
icon: ''
name: Link
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{linkText}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
