columnSuffix: null
handle: matrix
instructions: null
name: Matrix
searchable: false
settings:
  createButtonLabel: null
  defaultIndexViewMode: cards
  entryTypes:
    - 5a776f58-ff2b-470c-8725-cf8371fe83c3 # Headline
    - 5c9ccd7b-5bc6-4d52-865f-242e9ab64957 # Image Text
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
