columnSuffix: null
handle: openInNewTab
instructions: null
name: 'Open in New Tab'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
