columnSuffix: null
handle: richtext
instructions: null
name: Richtext
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 59fb6faa-0376-4921-878d-ebd1574897f2 # Default
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
