columnSuffix: null
handle: singleRelatedAddress
instructions: null
name: 'Single Related Address'
searchable: false
settings:
  maxAddresses: 1
  minAddresses: null
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Addresses
