defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5c9ccd7b-5bc6-4d52-865f-242e9ab64957 # Image Text
handle: exampleSection
maxAuthors: 1
name: 'Example Section'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3b255b6a-c7cb-4664-9be2-96a291406be0: # ES
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'example-section/{slug}'
  4e251c92-6bae-4905-b0f1-14fcf7169733: # DE
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'example-section/{slug}'
  f1b75f00-f4ed-4958-8a70-45714133b929: # EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'example-section/{slug}'
type: channel
