defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: bcbde2d8-bccd-4869-aa53-2c187016d6d1 # Default Fields
  -
    uid: 97eed79f-6960-47e8-86e7-375615a7070a # Relational Fields with Max Setting
handle: fieldCheck
maxAuthors: 1
name: 'Field Check'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  3b255b6a-c7cb-4664-9be2-96a291406be0: # ES
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'field-check/{slug}'
  4e251c92-6bae-4905-b0f1-14fcf7169733: # DE
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'field-check/{slug}'
  f1b75f00-f4ed-4958-8a70-45714133b929: # EN
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'field-check/{slug}'
type: channel
