cardView:
  - 'layoutElement:0c32705a-7b93-4496-8f34-81c42127db21'
tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-04-30T14:34:11+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 447297a6-b4ab-45bb-92b6-67e8dd5992eb
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-04-30T14:34:11+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 93b470ac-0f67-4e32-870c-3234a542ee95
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-04-30T14:34:11+00:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 0c32705a-7b93-4496-8f34-81c42127db21
        userCondition: null
        warning: null
    name: Content
    uid: d7597865-3035-4e0f-b01c-63c637c41fa4
    userCondition: null
